version: "3.8"

services:
  frontend:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./build/web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    restart: unless-stopped
    # No depende de api porque están en diferentes docker-compose
    # La comunicación se hace a través de la red compartida
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    external: true
