name: fct_frontend
description: Frontend Flutter para el sistema de gestión de proyectos FCT
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Gestión de Estado
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navegación (Estandarizado en auto_route)
  auto_route: ^9.2.0

  # Inyección de Dependencias
  get_it: ^7.6.4

  # Modelos y Serialización
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # HTTP Client
  dio: ^5.4.0

  # WebSockets
  web_socket_channel: ^2.4.0

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_markdown: ^0.6.18

  # Notificaciones
  flutter_local_notifications: ^16.3.0

  # Búsqueda
  fuse: ^0.0.99

  # Exportación de Datos
  excel: ^2.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  file_picker: ^6.1.1

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2

  # Internacionalización
  flutter_localizations:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.2
  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  intl_utils: ^2.8.5
  auto_route_generator: ^9.0.0

  # Testing
  integration_test:
    sdk: flutter
  mockito: ^5.4.4

  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/i18n/

  generate: true

# Configuración de localización
flutter_intl:
  enabled: true
  arb_dir: assets/i18n
  output_dir: lib/l10n
