name: fct_frontend
description: Sistema de Gestión de Proyectos FCT - Frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Localizations
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  
  # DI
  get_it: ^7.6.0
  
  # Storage
  shared_preferences: ^2.2.0
  
  # Navigation
  auto_route: ^7.8.0
  
  # WebSocket
  web_socket_channel: ^2.4.0
  
  # Models & Serialization
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0
  
  # HTTP Client
  dio: ^5.3.0
  
  # UI Components
  flutter_svg: ^2.0.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.0
  riverpod_generator: ^2.3.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  auto_route_generator: ^7.3.0
  
  # Testing
  mockito: ^5.4.0

flutter:
  uses-material-design: true
  
  # Assets (descomentar cuando los tengas)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Fonts (descomentar cuando las tengas)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf