name: Flutter CI

on:
  push:
    branches: [main, develop]
    paths:
      - "frontend/**"
      - ".github/workflows/flutter_ci.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "frontend/**"
      - ".github/workflows/flutter_ci.yml"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        working-directory: frontend
        run: flutter pub get

      - name: Generate code (build_runner)
        working-directory: frontend
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze
        working-directory: frontend
        run: flutter analyze

      - name: Run tests
        working-directory: frontend
        run: flutter test
